
import { KeyMap, Language } from "./types";

export const CONSTANTS = {
  TILE_SIZE: 48,
  ROOM_WIDTH: 15, 
  ROOM_HEIGHT: 9,
  CANVAS_WIDTH: 15 * 48, 
  CANVAS_HEIGHT: 9 * 48, 
  
  PLAYER_SIZE: 32,
  ENEMY_SIZE: 32,
  PROJECTILE_SIZE: 16, // Increased slightly for visibility
  ITEM_SIZE: 24,

  FPS: 60,
  
  // Revised Palette for Pixel Art Generation
  PALETTE: {
    // Environment
    BG: '#121212',
    WALL_BASE: '#2a2a2a',
    WALL_HIGHLIGHT: '#3d3d3d',
    WALL_SHADOW: '#1a1a1a',
    FLOOR_BASE: '#1c1c1c',
    FLOOR_VAR_1: '#222222',
    FLOOR_VAR_2: '#181818',
    ROCK_BASE: '#4a4a4a',
    ROCK_HIGHLIGHT: '#666666',
    
    // Doors
    DOOR_FRAME: '#4a3b2a',
    DOOR_LOCKED: '#2e2216',
    DOOR_OPEN: '#0f291e',

    // Player (Cyan/Blue Knight)
    PLAYER_MAIN: '#0ea5e9', // Sky 500
    PLAYER_SHADOW: '#0369a1', // Sky 700
    PLAYER_LIGHT: '#bae6fd', // Sky 200
    PLAYER_SKIN: '#fdba74', // Orange 300

    // Enemies
    ENEMY_RED_MAIN: '#ef4444', 
    ENEMY_RED_DARK: '#991b1b',
    ENEMY_BLUE_MAIN: '#3b82f6',
    ENEMY_BLUE_DARK: '#1e40af',
    ENEMY_GREEN_MAIN: '#65a30d',
    ENEMY_GREEN_DARK: '#3f6212',
    BOSS_MAIN: '#7f1d1d',
    BOSS_HIGHLIGHT: '#dc2626',

    // Items
    ITEM_GOLD: '#fbbf24',
    ITEM_SHADOW: '#b45309',
    HEART_MAIN: '#ef4444',
    HEART_SHADOW: '#991b1b',
    PEDESTAL_TOP: '#525252',
    PEDESTAL_SIDE: '#262626',
    
    // Projectiles
    PROJ_PLAYER_MAIN: '#60a5fa',
    PROJ_PLAYER_CORE: '#ffffff',
    PROJ_ENEMY_MAIN: '#f97316',
    PROJ_ENEMY_CORE: '#ffedd5',
  },
  
  // Keep legacy color ref for fallback/UI
  COLORS: {
      BG: '#1a1a1a',
      WALL: '#404040',
      FLOOR: '#262626',
      ROCK: '#525252',
      DOOR: '#78350f',
      DOOR_OPEN: '#14532d',
      TRAPDOOR: '#000000',
      PLAYER: '#06b6d4',
      PLAYER_HIT: '#cffafe',
      ENEMY: '#ef4444',
      ENEMY_FLYING: '#3b82f6',
      ENEMY_TANK: '#3f6212',
      ENEMY_ORBITER: '#db2777',
      ENEMY_BOSS: '#7f1d1d',
      PROJECTILE_FRIENDLY: '#3b82f6',
      PROJECTILE_ENEMY: '#f97316',
      ITEM: '#a855f7',
      HEART: '#dc2626',
      PEDESTAL: '#525252',
  }
};

export const DEFAULT_KEYMAP: KeyMap = {
  moveUp: 'KeyW',
  moveDown: 'KeyS',
  moveLeft: 'KeyA',
  moveRight: 'KeyD',
  shootUp: 'ArrowUp',
  shootDown: 'ArrowDown',
  shootLeft: 'ArrowLeft',
  shootRight: 'ArrowRight',
  restart: 'KeyR',
  pause: 'Escape'
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  [Language.ZH_CN]: {
    GAME_TITLE: "胎渊",
    START_RUN: "开始游戏",
    SETTINGS: "设置",
    HEALTH: "生命值",
    FLOOR: "层数",
    SCORE: "分数",
    MAP: "地图",
    ITEMS: "物品",
    GAME_OVER: "你死了",
    VICTORY: "胜利",
    TRY_AGAIN: "重试",
    RESTART_HINT: "长按 'R' 快速重开",
    HOLD_R: "长按 'R' 重置",
    
    // Pause Menu
    PAUSE_TITLE: "游戏暂停",
    RESUME: "继续游戏",
    RESTART: "重新开始",
    
    // Settings
    SETTING_TITLE: "设置",
    SETTING_LANG: "语言",
    SETTING_MINIMAP: "显示小地图",
    SETTING_KEYS: "按键设置",
    KEY_MOVE_UP: "上移",
    KEY_MOVE_DOWN: "下移",
    KEY_MOVE_LEFT: "左移",
    KEY_MOVE_RIGHT: "右移",
    KEY_SHOOT_UP: "上射",
    KEY_SHOOT_DOWN: "下射",
    KEY_SHOOT_LEFT: "左射",
    KEY_SHOOT_RIGHT: "右射",
    KEY_RESTART: "重开",
    KEY_PAUSE: "暂停",
    WAITING_FOR_KEY: "请按键...",
    CLOSE: "关闭",

    // Characters
    CHAR_ALPHA_NAME: "阿尔法",
    CHAR_ALPHA_DESC: "均衡的战士，一切的开始。",
    CHAR_TITAN_NAME: "泰坦",
    CHAR_TITAN_DESC: "高生命，高击退，但行动迟缓。",
    CHAR_STRIDER_NAME: "游侠",
    CHAR_STRIDER_DESC: "极快的速度，但比较脆弱。",
    CHAR_BLASTER_NAME: "爆破手",
    CHAR_BLASTER_DESC: "拥有散射能力，擅长群体控制。",
    CHAR_SNIPER_NAME: "鹰眼",
    CHAR_SNIPER_DESC: "超远射程，致命一击。",
    CHAR_SWARM_NAME: "蜂群",
    CHAR_SWARM_DESC: "四发散射，弹幕压制。",
    CHAR_VOID_NAME: "虚空",
    CHAR_VOID_DESC: "极致的伤害，触之即碎。",

    // Stats
    STAT_HP: "生命",
    STAT_SPEED: "移速",
    STAT_DMG: "伤害",
    STAT_RATE: "射速",
    STAT_RANGE: "射程",
    STAT_SHOT: "弹速",

    // Items
    ITEM_HP_UP_NAME: "鲜红的肉块",
    ITEM_HP_UP_DESC: "生命上限 +2，恢复生命",
    ITEM_SPEED_UP_NAME: "兴奋剂",
    ITEM_SPEED_UP_DESC: "移速 +0.5",
    ITEM_DAMAGE_UP_NAME: "铁刺",
    ITEM_DAMAGE_UP_DESC: "伤害 +10%",
    ITEM_FIRE_RATE_UP_NAME: "咖啡",
    ITEM_FIRE_RATE_UP_DESC: "射速 +20%",
    ITEM_SHOT_SPEED_UP_NAME: "弹簧",
    ITEM_SHOT_SPEED_UP_DESC: "弹速 +1.5",
    ITEM_RANGE_UP_NAME: "望远镜",
    ITEM_RANGE_UP_DESC: "射程 +20%",
    ITEM_BULLET_SIZE_UP_NAME: "铅球",
    ITEM_BULLET_SIZE_UP_DESC: "子弹变大 +50%",
    ITEM_TRIPLE_SHOT_NAME: "三眼",
    ITEM_TRIPLE_SHOT_DESC: "三发散射",
    ITEM_QUAD_SHOT_NAME: "复眼",
    ITEM_QUAD_SHOT_DESC: "四发散射",
    ITEM_KNOCKBACK_UP_NAME: "重拳手套",
    ITEM_KNOCKBACK_UP_DESC: "击退效果 +20%",
    ITEM_GLASS_CANNON_NAME: "玻璃大炮",
    ITEM_GLASS_CANNON_DESC: "伤害+100%，生命上限-2",
    
    PICKUP_HEART_NAME: "心脏",
    PICKUP_HEART_DESC: "恢复 1 格生命",
    NOTIF_RESTART: "旅程重置",
  },
  [Language.ZH_TW]: {
    GAME_TITLE: "胎淵",
    START_RUN: "開始遊戲",
    SETTINGS: "設置",
    HEALTH: "生命值",
    FLOOR: "層數",
    SCORE: "分數",
    MAP: "地圖",
    ITEMS: "物品",
    GAME_OVER: "你死了",
    VICTORY: "勝利",
    TRY_AGAIN: "重試",
    RESTART_HINT: "長按 'R' 快速重開",
    HOLD_R: "長按 'R' 重置",
    
    PAUSE_TITLE: "遊戲暫停",
    RESUME: "繼續遊戲",
    RESTART: "重新開始",
    
    SETTING_TITLE: "設置",
    SETTING_LANG: "語言",
    SETTING_MINIMAP: "顯示小地圖",
    SETTING_KEYS: "按鍵設置",
    KEY_MOVE_UP: "上移",
    KEY_MOVE_DOWN: "下移",
    KEY_MOVE_LEFT: "左移",
    KEY_MOVE_RIGHT: "右移",
    KEY_SHOOT_UP: "上射",
    KEY_SHOOT_DOWN: "下射",
    KEY_SHOOT_LEFT: "左射",
    KEY_SHOOT_RIGHT: "右射",
    KEY_RESTART: "重開",
    KEY_PAUSE: "暫停",
    WAITING_FOR_KEY: "請按鍵...",
    CLOSE: "關閉",

    CHAR_ALPHA_NAME: "阿爾法",
    CHAR_ALPHA_DESC: "均衡的戰士，一切的開始。",
    CHAR_TITAN_NAME: "泰坦",
    CHAR_TITAN_DESC: "高生命，高擊退，但行動遲緩。",
    CHAR_STRIDER_NAME: "遊俠",
    CHAR_STRIDER_DESC: "極快的速度，但比較脆弱。",
    CHAR_BLASTER_NAME: "爆破手",
    CHAR_BLASTER_DESC: "擁有散射能力，擅長群體控制。",
    CHAR_SNIPER_NAME: "鷹眼",
    CHAR_SNIPER_DESC: "超遠射程，致命一擊。",
    CHAR_SWARM_NAME: "蜂群",
    CHAR_SWARM_DESC: "四發散射，彈幕壓制。",
    CHAR_VOID_NAME: "虛空",
    CHAR_VOID_DESC: "極致的傷害，觸之即碎。",

    STAT_HP: "生命",
    STAT_SPEED: "移速",
    STAT_DMG: "傷害",
    STAT_RATE: "射速",
    STAT_RANGE: "射程",
    STAT_SHOT: "彈速",

    ITEM_HP_UP_NAME: "鮮紅的肉塊",
    ITEM_HP_UP_DESC: "生命上限 +2，恢復生命",
    ITEM_SPEED_UP_NAME: "興奮劑",
    ITEM_SPEED_UP_DESC: "移速 +0.5",
    ITEM_DAMAGE_UP_NAME: "鐵刺",
    ITEM_DAMAGE_UP_DESC: "傷害 +10%",
    ITEM_FIRE_RATE_UP_NAME: "咖啡",
    ITEM_FIRE_RATE_UP_DESC: "射速 +20%",
    ITEM_SHOT_SPEED_UP_NAME: "彈簧",
    ITEM_SHOT_SPEED_UP_DESC: "彈速 +1.5",
    ITEM_RANGE_UP_NAME: "望遠鏡",
    ITEM_RANGE_UP_DESC: "射程 +20%",
    ITEM_BULLET_SIZE_UP_NAME: "鉛球",
    ITEM_BULLET_SIZE_UP_DESC: "子彈變大 +50%",
    ITEM_TRIPLE_SHOT_NAME: "三眼",
    ITEM_TRIPLE_SHOT_DESC: "三發散射",
    ITEM_QUAD_SHOT_NAME: "複眼",
    ITEM_QUAD_SHOT_DESC: "四發散射",
    ITEM_KNOCKBACK_UP_NAME: "重拳手套",
    ITEM_KNOCKBACK_UP_DESC: "擊退效果 +20%",
    ITEM_GLASS_CANNON_NAME: "玻璃大炮",
    ITEM_GLASS_CANNON_DESC: "傷害+100%，生命上限-2",
    
    PICKUP_HEART_NAME: "心臟",
    PICKUP_HEART_DESC: "恢復 1 格生命",
    NOTIF_RESTART: "旅程重置",
  },
  [Language.EN]: {
    GAME_TITLE: "ABYSS OF ORIGINS",
    START_RUN: "START GAME",
    SETTINGS: "SETTINGS",
    HEALTH: "HEALTH",
    FLOOR: "FLOOR",
    SCORE: "SCORE",
    MAP: "MAP",
    ITEMS: "ITEMS",
    GAME_OVER: "YOU DIED",
    VICTORY: "VICTORY",
    TRY_AGAIN: "TRY AGAIN",
    RESTART_HINT: "Hold 'R' to Quick Restart",
    HOLD_R: "HOLD 'R' TO RESTART",

    PAUSE_TITLE: "PAUSED",
    RESUME: "RESUME",
    RESTART: "RESTART",

    SETTING_TITLE: "SETTINGS",
    SETTING_LANG: "Language",
    SETTING_MINIMAP: "Show Minimap",
    SETTING_KEYS: "Key Bindings",
    KEY_MOVE_UP: "Move Up",
    KEY_MOVE_DOWN: "Move Down",
    KEY_MOVE_LEFT: "Move Left",
    KEY_MOVE_RIGHT: "Move Right",
    KEY_SHOOT_UP: "Shoot Up",
    KEY_SHOOT_DOWN: "Shoot Down",
    KEY_SHOOT_LEFT: "Shoot Left",
    KEY_SHOOT_RIGHT: "Shoot Right",
    KEY_RESTART: "Restart",
    KEY_PAUSE: "Pause",
    WAITING_FOR_KEY: "Press any key...",
    CLOSE: "Close",

    CHAR_ALPHA_NAME: "Alpha",
    CHAR_ALPHA_DESC: "Balanced stats. The beginning.",
    CHAR_TITAN_NAME: "Titan",
    CHAR_TITAN_DESC: "High HP, high knockback, but slow.",
    CHAR_STRIDER_NAME: "Strider",
    CHAR_STRIDER_DESC: "Very fast, but fragile.",
    CHAR_BLASTER_NAME: "Blaster",
    CHAR_BLASTER_DESC: "Triple shot capability for crowd control.",
    CHAR_SNIPER_NAME: "Sniper",
    CHAR_SNIPER_DESC: "Extreme range and damage.",
    CHAR_SWARM_NAME: "Swarm",
    CHAR_SWARM_DESC: "Quad shot barrage.",
    CHAR_VOID_NAME: "Void",
    CHAR_VOID_DESC: "Glass cannon. Massive damage.",

    STAT_HP: "HP",
    STAT_SPEED: "SPD",
    STAT_DMG: "DMG",
    STAT_RATE: "RATE",
    STAT_RANGE: "RNG",
    STAT_SHOT: "SHOT",

    ITEM_HP_UP_NAME: "Raw Meat",
    ITEM_HP_UP_DESC: "Max HP +2, Heal",
    ITEM_SPEED_UP_NAME: "Stimulant",
    ITEM_SPEED_UP_DESC: "Speed +0.5",
    ITEM_DAMAGE_UP_NAME: "Iron Spike",
    ITEM_DAMAGE_UP_DESC: "Damage +10%",
    ITEM_FIRE_RATE_UP_NAME: "Coffee",
    ITEM_FIRE_RATE_UP_DESC: "Fire Rate +20%",
    ITEM_SHOT_SPEED_UP_NAME: "Spring",
    ITEM_SHOT_SPEED_UP_DESC: "Shot Speed +1.5",
    ITEM_RANGE_UP_NAME: "Binoculars",
    ITEM_RANGE_UP_DESC: "Range +20%",
    ITEM_BULLET_SIZE_UP_NAME: "Lead Ball",
    ITEM_BULLET_SIZE_UP_DESC: "Bullet Size +50%",
    ITEM_TRIPLE_SHOT_NAME: "Third Eye",
    ITEM_TRIPLE_SHOT_DESC: "Triple Shot",
    ITEM_QUAD_SHOT_NAME: "Compound Eye",
    ITEM_QUAD_SHOT_DESC: "Quad Shot",
    ITEM_KNOCKBACK_UP_NAME: "Heavy Glove",
    ITEM_KNOCKBACK_UP_DESC: "Knockback +20%",
    ITEM_GLASS_CANNON_NAME: "Glass Cannon",
    ITEM_GLASS_CANNON_DESC: "Damage +100%, Max HP -2",
    
    PICKUP_HEART_NAME: "Heart",
    PICKUP_HEART_DESC: "Recover 1 HP",
    NOTIF_RESTART: "RUN RESTARTED",
  },
  [Language.RU]: {
    GAME_TITLE: "БЕЗДНА ИСТОКОВ",
    START_RUN: "НАЧАТЬ ИГРУ",
    SETTINGS: "НАСТРОЙКИ",
    HEALTH: "ЗДОРОВЬЕ",
    FLOOR: "ЭТАЖ",
    SCORE: "СЧЕТ",
    MAP: "КАРТА",
    ITEMS: "ПРЕДМЕТЫ",
    GAME_OVER: "ВЫ ПОГИБЛИ",
    VICTORY: "ПОБЕДА",
    TRY_AGAIN: "ЗАНОВО",
    RESTART_HINT: "Удерж. 'R' для рестарта",
    HOLD_R: "УДЕРЖ. 'R' ДЛЯ РЕСТАРТА",

    PAUSE_TITLE: "ПАУЗА",
    RESUME: "ПРОДОЛЖИТЬ",
    RESTART: "ЗАНОВО",

    SETTING_TITLE: "НАСТРОЙКИ",
    SETTING_LANG: "Язык",
    SETTING_MINIMAP: "Миникарта",
    SETTING_KEYS: "Управление",
    KEY_MOVE_UP: "Вверх",
    KEY_MOVE_DOWN: "Вниз",
    KEY_MOVE_LEFT: "Влево",
    KEY_MOVE_RIGHT: "Вправо",
    KEY_SHOOT_UP: "Стрелять Вверх",
    KEY_SHOOT_DOWN: "Стрелять Вниз",
    KEY_SHOOT_LEFT: "Стрелять Влево",
    KEY_SHOOT_RIGHT: "Стрелять Вправо",
    KEY_RESTART: "Рестарт",
    KEY_PAUSE: "Пауза",
    WAITING_FOR_KEY: "Нажмите клавишу...",
    CLOSE: "Закрыть",

    CHAR_ALPHA_NAME: "Альфа",
    CHAR_ALPHA_DESC: "Сбалансированный воин.",
    CHAR_TITAN_NAME: "Титан",
    CHAR_TITAN_DESC: "Много ОЗ, сильное отбрасывание, медленный.",
    CHAR_STRIDER_NAME: "Страйдер",
    CHAR_STRIDER_DESC: "Очень быстрый, но хрупкий.",
    CHAR_BLASTER_NAME: "Подрывник",
    CHAR_BLASTER_DESC: "Тройной выстрел для контроля толпы.",
    CHAR_SNIPER_NAME: "Снайпер",
    CHAR_SNIPER_DESC: "Огромная дальность и урон.",
    CHAR_SWARM_NAME: "Рой",
    CHAR_SWARM_DESC: "Четверной залп.",
    CHAR_VOID_NAME: "Пустота",
    CHAR_VOID_DESC: "Стеклянная пушка. Колоссальный урон.",

    STAT_HP: "ОЗ",
    STAT_SPEED: "СКР",
    STAT_DMG: "УРОН",
    STAT_RATE: "СКОР",
    STAT_RANGE: "ДАЛЬ",
    STAT_SHOT: "СНАР",

    ITEM_HP_UP_NAME: "Сырое Мясо",
    ITEM_HP_UP_DESC: "Макс ОЗ +2, Лечение",
    ITEM_SPEED_UP_NAME: "Стимулятор",
    ITEM_SPEED_UP_DESC: "Скорость +0.5",
    ITEM_DAMAGE_UP_NAME: "Шип",
    ITEM_DAMAGE_UP_DESC: "Урон +10%",
    ITEM_FIRE_RATE_UP_NAME: "Кофе",
    ITEM_FIRE_RATE_UP_DESC: "Скоростр. +20%",
    ITEM_SHOT_SPEED_UP_NAME: "Пружина",
    ITEM_SHOT_SPEED_UP_DESC: "Скор. пули +1.5",
    ITEM_RANGE_UP_NAME: "Бинокль",
    ITEM_RANGE_UP_DESC: "Дальность +20%",
    ITEM_BULLET_SIZE_UP_NAME: "Свинец",
    ITEM_BULLET_SIZE_UP_DESC: "Размер пули +50%",
    ITEM_TRIPLE_SHOT_NAME: "Третий Глаз",
    ITEM_TRIPLE_SHOT_DESC: "Тройной Выстрел",
    ITEM_QUAD_SHOT_NAME: "Фасетчатый Глаз",
    ITEM_QUAD_SHOT_DESC: "Четверной Выстрел",
    ITEM_KNOCKBACK_UP_NAME: "Тяжелая Перчатка",
    ITEM_KNOCKBACK_UP_DESC: "Отбрасывание +20%",
    ITEM_GLASS_CANNON_NAME: "Стеклянная Пушка",
    ITEM_GLASS_CANNON_DESC: "Урон +100%, Макс ОЗ -2",

    PICKUP_HEART_NAME: "Сердце",
    PICKUP_HEART_DESC: "Восст. 1 ОЗ",
    NOTIF_RESTART: "РЕСТАРТ",
  }
};
