import { KeyMap, Language } from "./types";

export const CONSTANTS = {
  TILE_SIZE: 48,
  ROOM_WIDTH: 15, 
  ROOM_HEIGHT: 9,
  CANVAS_WIDTH: 15 * 48, 
  CANVAS_HEIGHT: 9 * 48, 
  
  PLAYER_SIZE: 32,
  ENEMY_SIZE: 32,
  PROJECTILE_SIZE: 16, // Increased slightly for visibility
  ITEM_SIZE: 24,

  FPS: 60,
  
  // Revised Palette for Pixel Art Generation
  PALETTE: {
    // Environment
    BG: '#121212',
    WALL_BASE: '#2a2a2a',
    WALL_HIGHLIGHT: '#3d3d3d',
    WALL_SHADOW: '#1a1a1a',
    FLOOR_BASE: '#1c1c1c',
    FLOOR_VAR_1: '#222222',
    FLOOR_VAR_2: '#181818',
    ROCK_BASE: '#4a4a4a',
    ROCK_HIGHLIGHT: '#666666',
    
    // Doors
    DOOR_FRAME: '#4a3b2a',
    DOOR_LOCKED: '#2e2216',
    DOOR_OPEN: '#0f291e',

    // Player (Cyan/Blue Knight)
    PLAYER_MAIN: '#0ea5e9', // Sky 500
    PLAYER_SHADOW: '#0369a1', // Sky 700
    PLAYER_LIGHT: '#bae6fd', // Sky 200
    PLAYER_SKIN: '#fdba74', // Orange 300

    // Enemies
    ENEMY_RED_MAIN: '#ef4444', 
    ENEMY_RED_DARK: '#991b1b',
    ENEMY_BLUE_MAIN: '#3b82f6',
    ENEMY_BLUE_DARK: '#1e40af',
    ENEMY_GREEN_MAIN: '#65a30d',
    ENEMY_GREEN_DARK: '#3f6212',
    BOSS_MAIN: '#7f1d1d',
    BOSS_HIGHLIGHT: '#dc2626',

    // Items
    ITEM_GOLD: '#fbbf24',
    ITEM_SHADOW: '#b45309',
    HEART_MAIN: '#ef4444',
    HEART_SHADOW: '#991b1b',
    
    // Projectiles
    PROJ_PLAYER_MAIN: '#60a5fa',
    PROJ_PLAYER_CORE: '#ffffff',
    PROJ_ENEMY_MAIN: '#f97316',
    PROJ_ENEMY_CORE: '#ffedd5',
  },
  
  // Keep legacy color ref for fallback/UI
  COLORS: {
      BG: '#1a1a1a',
      WALL: '#404040',
      FLOOR: '#262626',
      ROCK: '#525252',
      DOOR: '#78350f',
      DOOR_OPEN: '#14532d',
      TRAPDOOR: '#000000',
      PLAYER: '#06b6d4',
      PLAYER_HIT: '#cffafe',
      ENEMY: '#ef4444',
      ENEMY_FLYING: '#3b82f6',
      ENEMY_TANK: '#3f6212',
      ENEMY_ORBITER: '#db2777',
      ENEMY_BOSS: '#7f1d1d',
      PROJECTILE_FRIENDLY: '#3b82f6',
      PROJECTILE_ENEMY: '#f97316',
      ITEM: '#a855f7',
      HEART: '#dc2626',
  }
};

export const DEFAULT_KEYMAP: KeyMap = {
  moveUp: 'KeyW',
  moveDown: 'KeyS',
  moveLeft: 'KeyA',
  moveRight: 'KeyD',
  shootUp: 'ArrowUp',
  shootDown: 'ArrowDown',
  shootLeft: 'ArrowLeft',
  shootRight: 'ArrowRight',
  restart: 'KeyR'
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  [Language.ZH_CN]: {
    GAME_TITLE: "胎渊",
    START_RUN: "开始旅程",
    SETTINGS: "设置",
    HEALTH: "生命值",
    FLOOR: "层数",
    SCORE: "分数",
    MAP: "地图",
    ITEMS: "物品",
    GAME_OVER: "你死了",
    VICTORY: "胜利",
    TRY_AGAIN: "重试",
    RESTART_HINT: "长按 'R' 快速重开",
    HOLD_R: "长按 'R' 重置",
    
    // Settings
    SETTING_TITLE: "设置",
    SETTING_LANG: "语言",
    SETTING_MINIMAP: "显示小地图",
    SETTING_KEYS: "按键设置",
    KEY_MOVE_UP: "上移",
    KEY_MOVE_DOWN: "下移",
    KEY_MOVE_LEFT: "左移",
    KEY_MOVE_RIGHT: "右移",
    KEY_SHOOT_UP: "上射",
    KEY_SHOOT_DOWN: "下射",
    KEY_SHOOT_LEFT: "左射",
    KEY_SHOOT_RIGHT: "右射",
    KEY_RESTART: "重开",
    WAITING_FOR_KEY: "请按键...",
    CLOSE: "关闭",

    // Items
    ITEM_HP_UP_NAME: "鲜红的肉块",
    ITEM_HP_UP_DESC: "生命上限 +2，恢复生命",
    ITEM_SPEED_UP_NAME: "兴奋剂",
    ITEM_SPEED_UP_DESC: "移速 +0.5",
    ITEM_DAMAGE_UP_NAME: "铁刺",
    ITEM_DAMAGE_UP_DESC: "伤害 +10%",
    ITEM_FIRE_RATE_UP_NAME: "咖啡",
    ITEM_FIRE_RATE_UP_DESC: "射速 +20%",
    ITEM_SHOT_SPEED_UP_NAME: "弹簧",
    ITEM_SHOT_SPEED_UP_DESC: "弹速 +1.5",
    ITEM_RANGE_UP_NAME: "望远镜",
    ITEM_RANGE_UP_DESC: "射程 +20%",
    ITEM_BULLET_SIZE_UP_NAME: "铅球",
    ITEM_BULLET_SIZE_UP_DESC: "子弹变大 +50%",
    ITEM_TRIPLE_SHOT_NAME: "三眼",
    ITEM_TRIPLE_SHOT_DESC: "三发散射",
    ITEM_QUAD_SHOT_NAME: "复眼",
    ITEM_QUAD_SHOT_DESC: "四发散射",
    ITEM_KNOCKBACK_UP_NAME: "重拳手套",
    ITEM_KNOCKBACK_UP_DESC: "击退效果 +20%",
    
    PICKUP_HEART_NAME: "心脏",
    PICKUP_HEART_DESC: "恢复 1 格生命",
    NOTIF_RESTART: "旅程重置",
  },
  [Language.ZH_TW]: {
    GAME_TITLE: "胎淵",
    START_RUN: "開始旅程",
    SETTINGS: "設置",
    HEALTH: "生命值",
    FLOOR: "層數",
    SCORE: "分數",
    MAP: "地圖",
    ITEMS: "物品",
    GAME_OVER: "你死了",
    VICTORY: "勝利",
    TRY_AGAIN: "重試",
    RESTART_HINT: "長按 'R' 快速重開",
    HOLD_R: "長按 'R' 重置",
    
    SETTING_TITLE: "設置",
    SETTING_LANG: "語言",
    SETTING_MINIMAP: "顯示小地圖",
    SETTING_KEYS: "按鍵設置",
    KEY_MOVE_UP: "上移",
    KEY_MOVE_DOWN: "下移",
    KEY_MOVE_LEFT: "左移",
    KEY_MOVE_RIGHT: "右移",
    KEY_SHOOT_UP: "上射",
    KEY_SHOOT_DOWN: "下射",
    KEY_SHOOT_LEFT: "左射",
    KEY_SHOOT_RIGHT: "右射",
    KEY_RESTART: "重開",
    WAITING_FOR_KEY: "請按鍵...",
    CLOSE: "關閉",

    ITEM_HP_UP_NAME: "鮮紅的肉塊",
    ITEM_HP_UP_DESC: "生命上限 +2，恢復生命",
    ITEM_SPEED_UP_NAME: "興奮劑",
    ITEM_SPEED_UP_DESC: "移速 +0.5",
    ITEM_DAMAGE_UP_NAME: "鐵刺",
    ITEM_DAMAGE_UP_DESC: "傷害 +10%",
    ITEM_FIRE_RATE_UP_NAME: "咖啡",
    ITEM_FIRE_RATE_UP_DESC: "射速 +20%",
    ITEM_SHOT_SPEED_UP_NAME: "彈簧",
    ITEM_SHOT_SPEED_UP_DESC: "彈速 +1.5",
    ITEM_RANGE_UP_NAME: "望遠鏡",
    ITEM_RANGE_UP_DESC: "射程 +20%",
    ITEM_BULLET_SIZE_UP_NAME: "鉛球",
    ITEM_BULLET_SIZE_UP_DESC: "子彈變大 +50%",
    ITEM_TRIPLE_SHOT_NAME: "三眼",
    ITEM_TRIPLE_SHOT_DESC: "三發散射",
    ITEM_QUAD_SHOT_NAME: "複眼",
    ITEM_QUAD_SHOT_DESC: "四發散射",
    ITEM_KNOCKBACK_UP_NAME: "重拳手套",
    ITEM_KNOCKBACK_UP_DESC: "擊退效果 +20%",
    
    PICKUP_HEART_NAME: "心臟",
    PICKUP_HEART_DESC: "恢復 1 格生命",
    NOTIF_RESTART: "旅程重置",
  },
  [Language.EN]: {
    GAME_TITLE: "ABYSS OF ORIGINS",
    START_RUN: "START RUN",
    SETTINGS: "SETTINGS",
    HEALTH: "HEALTH",
    FLOOR: "FLOOR",
    SCORE: "SCORE",
    MAP: "MAP",
    ITEMS: "ITEMS",
    GAME_OVER: "YOU DIED",
    VICTORY: "VICTORY",
    TRY_AGAIN: "TRY AGAIN",
    RESTART_HINT: "Hold 'R' to Quick Restart",
    HOLD_R: "HOLD 'R' TO RESTART",

    SETTING_TITLE: "SETTINGS",
    SETTING_LANG: "Language",
    SETTING_MINIMAP: "Show Minimap",
    SETTING_KEYS: "Key Bindings",
    KEY_MOVE_UP: "Move Up",
    KEY_MOVE_DOWN: "Move Down",
    KEY_MOVE_LEFT: "Move Left",
    KEY_MOVE_RIGHT: "Move Right",
    KEY_SHOOT_UP: "Shoot Up",
    KEY_SHOOT_DOWN: "Shoot Down",
    KEY_SHOOT_LEFT: "Shoot Left",
    KEY_SHOOT_RIGHT: "Shoot Right",
    KEY_RESTART: "Restart",
    WAITING_FOR_KEY: "Press any key...",
    CLOSE: "Close",

    ITEM_HP_UP_NAME: "Raw Meat",
    ITEM_HP_UP_DESC: "Max HP +2, Heal",
    ITEM_SPEED_UP_NAME: "Stimulant",
    ITEM_SPEED_UP_DESC: "Speed +0.5",
    ITEM_DAMAGE_UP_NAME: "Iron Spike",
    ITEM_DAMAGE_UP_DESC: "Damage +10%",
    ITEM_FIRE_RATE_UP_NAME: "Coffee",
    ITEM_FIRE_RATE_UP_DESC: "Fire Rate +20%",
    ITEM_SHOT_SPEED_UP_NAME: "Spring",
    ITEM_SHOT_SPEED_UP_DESC: "Shot Speed +1.5",
    ITEM_RANGE_UP_NAME: "Binoculars",
    ITEM_RANGE_UP_DESC: "Range +20%",
    ITEM_BULLET_SIZE_UP_NAME: "Lead Ball",
    ITEM_BULLET_SIZE_UP_DESC: "Bullet Size +50%",
    ITEM_TRIPLE_SHOT_NAME: "Third Eye",
    ITEM_TRIPLE_SHOT_DESC: "Triple Shot",
    ITEM_QUAD_SHOT_NAME: "Compound Eye",
    ITEM_QUAD_SHOT_DESC: "Quad Shot",
    ITEM_KNOCKBACK_UP_NAME: "Heavy Glove",
    ITEM_KNOCKBACK_UP_DESC: "Knockback +20%",
    
    PICKUP_HEART_NAME: "Heart",
    PICKUP_HEART_DESC: "Recover 1 HP",
    NOTIF_RESTART: "RUN RESTARTED",
  },
  [Language.RU]: {
    GAME_TITLE: "БЕЗДНА ИСТОКОВ",
    START_RUN: "НАЧАТЬ",
    SETTINGS: "НАСТРОЙКИ",
    HEALTH: "ЗДОРОВЬЕ",
    FLOOR: "ЭТАЖ",
    SCORE: "СЧЕТ",
    MAP: "КАРТА",
    ITEMS: "ПРЕДМЕТЫ",
    GAME_OVER: "ВЫ ПОГИБЛИ",
    VICTORY: "ПОБЕДА",
    TRY_AGAIN: "ЗАНОВО",
    RESTART_HINT: "Удерж. 'R' для рестарта",
    HOLD_R: "УДЕРЖ. 'R' ДЛЯ РЕСТАРТА",

    SETTING_TITLE: "НАСТРОЙКИ",
    SETTING_LANG: "Язык",
    SETTING_MINIMAP: "Миникарта",
    SETTING_KEYS: "Управление",
    KEY_MOVE_UP: "Вверх",
    KEY_MOVE_DOWN: "Вниз",
    KEY_MOVE_LEFT: "Влево",
    KEY_MOVE_RIGHT: "Вправо",
    KEY_SHOOT_UP: "Стрелять Вверх",
    KEY_SHOOT_DOWN: "Стрелять Вниз",
    KEY_SHOOT_LEFT: "Стрелять Влево",
    KEY_SHOOT_RIGHT: "Стрелять Вправо",
    KEY_RESTART: "Рестарт",
    WAITING_FOR_KEY: "Нажмите клавишу...",
    CLOSE: "Закрыть",

    ITEM_HP_UP_NAME: "Сырое Мясо",
    ITEM_HP_UP_DESC: "Макс ОЗ +2, Лечение",
    ITEM_SPEED_UP_NAME: "Стимулятор",
    ITEM_SPEED_UP_DESC: "Скорость +0.5",
    ITEM_DAMAGE_UP_NAME: "Шип",
    ITEM_DAMAGE_UP_DESC: "Урон +10%",
    ITEM_FIRE_RATE_UP_NAME: "Кофе",
    ITEM_FIRE_RATE_UP_DESC: "Скоростр. +20%",
    ITEM_SHOT_SPEED_UP_NAME: "Пружина",
    ITEM_SHOT_SPEED_UP_DESC: "Скор. пули +1.5",
    ITEM_RANGE_UP_NAME: "Бинокль",
    ITEM_RANGE_UP_DESC: "Дальность +20%",
    ITEM_BULLET_SIZE_UP_NAME: "Свинец",
    ITEM_BULLET_SIZE_UP_DESC: "Размер пули +50%",
    ITEM_TRIPLE_SHOT_NAME: "Третий Глаз",
    ITEM_TRIPLE_SHOT_DESC: "Тройной Выстрел",
    ITEM_QUAD_SHOT_NAME: "Фасетчатый Глаз",
    ITEM_QUAD_SHOT_DESC: "Четверной Выстрел",
    ITEM_KNOCKBACK_UP_NAME: "Тяжелая Перчатка",
    ITEM_KNOCKBACK_UP_DESC: "Отбрасывание +20%",

    PICKUP_HEART_NAME: "Сердце",
    PICKUP_HEART_DESC: "Восст. 1 ОЗ",
    NOTIF_RESTART: "РЕСТАРТ",
  }
};